# Generated by Django 5.2.14 on 2026-05-28 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_address_latitude_address_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='court',
            name='name',
        ),
        migrations.RemoveField(
            model_name='favoritegame',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='favoritegame',
            name='id',
        ),
        migrations.RemoveField(
            model_name='favoritevenue',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gamematch',
            name='weather_index',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='useravailability',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usersportlevel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='base_price',
        ),
        migrations.AddField(
            model_name='court',
            name='base_price',
            field=models.IntegerField(db_column='base_price', default=0),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='weather',
            field=models.JSONField(blank=True, db_column='weather', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='match',
            field=models.ForeignKey(db_column='game_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api_v1.gamematch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(db_column='message', default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.AutoField(db_column='address_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='id',
            field=models.AutoField(db_column='blacklist_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='court',
            name='id',
            field=models.AutoField(db_column='court_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='court',
            name='venue',
            field=models.ForeignKey(db_column='venue_id', on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='api_v1.venue'),
        ),
        migrations.AlterField(
            model_name='courtconflict',
            name='court1',
            field=models.ForeignKey(db_column='court_id_1', on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_1', to='api_v1.court'),
        ),
        migrations.AlterField(
            model_name='courtconflict',
            name='court2',
            field=models.ForeignKey(db_column='court_id_2', on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_2', to='api_v1.court'),
        ),
        migrations.AlterField(
            model_name='courtconflict',
            name='id',
            field=models.AutoField(db_column='conflict_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facility',
            name='id',
            field=models.AutoField(db_column='facility_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favoritegame',
            name='match',
            field=models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='api_v1.gamematch'),
        ),
        migrations.AlterField(
            model_name='favoritegame',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='favorite_games', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoritevenue',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='favorite_venues', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoritevenue',
            name='venue',
            field=models.ForeignKey(db_column='venue_id', on_delete=django.db.models.deletion.CASCADE, to='api_v1.venue'),
        ),
        migrations.AlterField(
            model_name='gamematch',
            name='court',
            field=models.ForeignKey(blank=True, db_column='court_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.court'),
        ),
        migrations.AlterField(
            model_name='gamematch',
            name='id',
            field=models.AutoField(db_column='game_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gamematch',
            name='sport',
            field=models.ForeignKey(db_column='sport_id', on_delete=django.db.models.deletion.CASCADE, to='api_v1.sport'),
        ),
        migrations.AlterField(
            model_name='matchparticipant',
            name='id',
            field=models.AutoField(db_column='list_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchparticipant',
            name='match',
            field=models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api_v1.gamematch'),
        ),
        migrations.AlterField(
            model_name='matchparticipant',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchwaitlist',
            name='id',
            field=models.AutoField(db_column='waitlist_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchwaitlist',
            name='match',
            field=models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='api_v1.gamematch'),
        ),
        migrations.AlterField(
            model_name='matchwaitlist',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(db_column='notification_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='penaltyrule',
            name='id',
            field=models.AutoField(db_column='rule_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(db_column='report_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='match',
            field=models.ForeignKey(db_column='game_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.gamematch'),
        ),
        migrations.AlterField(
            model_name='report',
            name='offender',
            field=models.ForeignKey(db_column='offender_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(db_column='reporter_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='rule',
            field=models.ForeignKey(blank=True, db_column='rule_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.penaltyrule'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='id',
            field=models.AutoField(db_column='sport_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(db_column='sport_name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, db_column='birth_date', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(db_column='user_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useravailability',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='availability', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersportlevel',
            name='level',
            field=models.CharField(choices=[('C(beginner)', 'Beginner'), ('B(advanced)', 'Advanced'), ('A(Veteran)', 'Veteran'), ('S(Elite)', 'Elite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usersportlevel',
            name='sport',
            field=models.ForeignKey(db_column='sport_id', on_delete=django.db.models.deletion.CASCADE, to='api_v1.sport'),
        ),
        migrations.AlterField(
            model_name='usersportlevel',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sport_levels', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.ForeignKey(blank=True, db_column='address_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to='api_v1.address'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='id',
            field=models.AutoField(db_column='venue_id', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='blacklist',
            table='blacklist',
        ),
        migrations.AlterModelTable(
            name='court',
            table='court',
        ),
        migrations.AlterModelTable(
            name='courtconflict',
            table='court_conflicts',
        ),
        migrations.AlterModelTable(
            name='facility',
            table='facilities',
        ),
        migrations.AlterModelTable(
            name='favoritevenue',
            table='favorite_venues',
        ),
        migrations.AlterModelTable(
            name='gamematch',
            table='gamesmatches',
        ),
        migrations.AlterModelTable(
            name='matchparticipant',
            table='match_participants',
        ),
        migrations.AlterModelTable(
            name='matchwaitlist',
            table='match_waitlist',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notification',
        ),
        migrations.AlterModelTable(
            name='penaltyrule',
            table='penalty_rules',
        ),
        migrations.AlterModelTable(
            name='report',
            table='reports',
        ),
        migrations.AlterModelTable(
            name='sport',
            table='sports',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='useravailability',
            table='user_availability',
        ),
        migrations.AlterModelTable(
            name='usersportlevel',
            table='user_sport_levels',
        ),
        migrations.AlterModelTable(
            name='venue',
            table='venues',
        ),
        migrations.AlterModelTable(
            name='weatherdata',
            table='weather_data',
        ),
    ]
