# Generated by Django 5.2.14 on 2026-05-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_announcement_gamematch_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamematch',
            name='gender_limit',
            field=models.CharField(default='不限', max_length=20),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='venue_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='venue_status',
            field=models.CharField(default='未確認', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gamematch',
            name='target_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('casual', 'Casual'), ('advanced', 'Advanced'), ('S', 'Elite'), ('A', 'Veteran'), ('B', 'Advanced'), ('C', 'Beginner')], max_length=20),
        ),
    ]
