# Generated by Django 6.0.5 on 2026-06-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0006_announcement_feedback_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='blacklist',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='court',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='courtconflict',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='favoritegame',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='gamebulletin',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='gamematch',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='matchparticipant',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='penaltyrule',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usersportlevel',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'managed': True},
        ),
    ]
