# Generated by Django 6.0.5 on 2026-06-08 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0007_alter_address_options_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='photo',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(db_column='user_id', db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(default='建議', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamematch',
            name='match_status',
            field=models.CharField(choices=[('recruiting', 'Recruiting'), ('full', 'Full'), ('closed', 'Closed'), ('started', 'Started'), ('failed_to_start', 'Failed to Start')], default='recruiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='match',
            field=models.ForeignKey(blank=True, db_column='game_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api_v1.gamematch'),
        ),
        migrations.AlterField(
            model_name='usersportlevel',
            name='level',
            field=models.CharField(choices=[('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S')], max_length=20),
        ),
    ]
