# Generated by Django 6.0.5 on 2026-06-10 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0008_announcement_photo_feedback_admin_reply_and_more'),
        ('api_v1', '0010_announcement_feedback_alter_address_options_and_more'),
    ]

    operations = [
    ]
