# Generated by Django 6.0.5 on 2026-06-10 12:18

import os
from django.db import migrations, models

IS_MANAGED = os.environ.get('FORCE_SQLITE') == 'True'

class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0011_merge_20260610_1555'),
        ('api_v1', '0011_feedbacktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='TaiwanRegion',
            fields=[
                ('id', models.AutoField(db_column='region_id', primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'taiwan_regions',
                'managed': IS_MANAGED,
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'managed': IS_MANAGED},
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'managed': IS_MANAGED},
        ),
        migrations.AlterModelOptions(
            name='blacklist',
            options={'managed': IS_MANAGED},
        ),
        migrations.AlterModelOptions(
            name='court',
            options={'managed': IS_MANAGED},
        ),
        migrations.AlterModelOptions(
            name='courtconflict',
            options={'managed': IS_MANAGED},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'managed': IS_MANAGED},
        ),
        migrations.AlterModelOptions(
            name='favoritegame',
            options={'managed': IS_MANAGED},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': IS_MANAGED},
        ),
        migrations.AlterModelOptions(
            name='gamebulletin',
            options={'managed': IS_MANAGED},
        ),
        migrations.AlterModelOptions(
            name='gamematch',
            options={'managed': IS_MANAGED},
        ),
        migrations.AlterModelOptions(
            name='matchparticipant',
            options={'managed': IS_MANAGED},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': IS_MANAGED},
        ),
        migrations.AlterModelOptions(
            name='penaltyrule',
            options={'managed': IS_MANAGED},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'managed': IS_MANAGED},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'managed': IS_MANAGED},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': IS_MANAGED},
        ),
        migrations.AlterModelOptions(
            name='usersportlevel',
            options={'managed': IS_MANAGED},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'managed': IS_MANAGED},
        ),
    ]
