# Generated by Django 6.0.5 on 2026-06-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0011_merge_20260610_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackType',
            fields=[
                ('id', models.AutoField(db_column='type_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'feedback_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaiwanRegion',
            fields=[
                ('id', models.AutoField(db_column='region_id', primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'taiwan_regions',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='blacklist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='court',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='courtconflict',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='favoritegame',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gamebulletin',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gamematch',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='matchparticipant',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='penaltyrule',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usersportlevel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'managed': False},
        ),
    ]
