# Generated by Django 6.0.5 on 2026-06-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0011_feedbacktype'),
        ('api_v1', '0012_feedbacktype_taiwanregion_alter_address_options_and_more'),
    ]

    operations = [
    ]
