# Generated by Django 6.0.5 on 2026-06-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0011_merge_20260610_1937'),
        ('api_v1', '0013_merge_20260610_2228'),
    ]

    operations = [
    ]
