# Generated by Django 6.0.5 on 2026-06-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0014_merge_20260610_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacktype',
            options={'managed': False},
        ),
    ]
