# Generated by Django 6.0.5 on 2026-06-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0016_migrate_coordinates_to_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taiwanregion',
            name='id',
        ),
        migrations.AddField(
            model_name='taiwanregion',
            name='zipcode',
            field=models.CharField(db_column='zipcode', max_length=5, primary_key=True, serialize=False),
        ),
    ]
