# Generated by Django 6.0.5 on 2026-06-12 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0017_taiwanregion_zipcode_as_pk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacktype',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='district',
        ),
        migrations.RemoveField(
            model_name='address',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='address',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='types',
        ),
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.ForeignKey(blank=True, db_column='zipcode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.taiwanregion'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.ForeignKey(blank=True, db_column='address_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='api_v1.address'),
        ),
        migrations.AlterUniqueTogether(
            name='taiwanregion',
            unique_together={('city', 'district')},
        ),
    ]
