# Generated by Django 6.0.5 on 2026-06-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0018_alter_feedbacktype_options_remove_address_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacktype',
            options={'managed': False},
        ),
    ]
