# Generated by Django 6.0.5 on 2026-06-14 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0019_alter_feedbacktype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacktype',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.ForeignKey(blank=True, db_column='feedback_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks_temp', to='api_v1.feedbacktype'),
        ),
    ]
